### ISSUE TITLE
User, Message and Chat Room?

### ISSUE THREAD

**Issue by HannaGirmaYas** [issue-one/appia_flutter#2]
User has a Username , Map of usernames to last message time, List of blocked usernames

```dart
 class User {
  String username;
  Map<String, DateTime> connections; // If we don’t have a chatroom class
  List<String> blockedUsers; 
}
```

Methods:

```getUser(username) // return a user(itself)
Search User(username) // return the searched user
Block User(username) // return confirmation
```
```dart
 class Message {
  //id
  int chatID;
  String recieverUsername;
  String senderUsername;
  String text;
  DateTime date;
}

class ChatRoom {
//id
  List<User> users;
  List<Messages> messages;
}
class User{
  List<ChatRoom> chats; 
}
```

A user has List of Chats...
A chat has list of messages...

Methods:
```
getLastMessage(chat_id)
loadMessages() // getMessages(chat_id)
sendMessage(chat_id, senderUsername)
```

**Comment by Yohe-Am** [comment]
> User has a Username , Map of usernames to last message time, List of blocked usernames
> 
> ```dart
>  class User {
>   String username;
>   Map<String, DateTime> connections; // If we don’t have a chatroom class
>   List<String> blockedUsers; 
>   List<ChatRoom> chats; 
> }
> ```

My primary complaint would be that you're using the User class to store most of the data. And data that doesn't make a lot of sense in most contexts. And if we're ever sending it over the wire, we'd be serializing a lot.

In fact, you didn't need to very Dart like in your approach. But if we're doing that, do consider more of the architecture. We'll be making use of repositories and blocs. How would access the different pieces in such a program? Most of the functionality would be put in the blocs and most of our classes would be dumb containers. Our User class would most likely be a plain class that describes a user. Such considerations would lead you to a somewhat different design.

Get rid of the functions and just design plain data classes and their relationships. What fields each class would have and such.

Otherwise, the content is pretty fine. Everyone subscribe to this issue and we'll refine it all as we go.
